version: '3'
services:
  apt-cacher:
    container_name: apt-cacher
    image: sameersbn/apt-cacher-ng
    ports:
    - 3142:3142
    volumes:
    - ./cache:/var/cache/apt-cacher-ng:rw
    - ./log:/var/log/apt-cacher-ng/:rw
    restart: always